services:
  app:
    build: .
    ports:
      - "8000:8000"
    environment:
      - REDIS_NODES=redis://redis-node-1:6379,redis://redis-node-2:6379
      - DEBUG=true
    depends_on:
      - redis-node-1
      - redis-node-2

  redis-node-1:
    image: redis:8.4.0
    ports:
      - "7000:6379"
    volumes:
      - redis1_data:/data

  redis-node-2:
    image: redis:8.4.0
    ports:
      - "7001:6379"
    volumes:
      - redis2_data:/data

volumes:
  redis1_data:
  redis2_data:
